### PR TITLE
Addressed null pointer exceptions

### PR DESCRIPTION
**Pull request by mcoburnwa**
In my environment I was experiencing some null pointer exceptions which I addressed in this commit.  Feel free to pull these in if they look good to you.

### CODE REVIEW

**Comment by planestraveler** [comment]
Thank everything seem in check with those fix.

**Comment by mcoburnwa** [comment]
Thanks I appreciate it.  I'd like to see about migrating CRs to TFS and possibly associations between CRs and modified source code.  Can you tell me what level of support the tool has for this?  If there is a better place to pose this question let me know.

Sent from my iPhone

On Dec 2, 2016, at 11:41 AM, Steve Tousignant <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #60<https://github.com/planestraveler/git-starteam/pull/60>.

**Comment by planestraveler** [comment]
To come back on your question. The way CR act on the commit from Starteam is by replacing the message of one or multiple files based on a regular expression. It was design in such a way that one file get the full description of the Change Request in its commit instead of an automated system commit.

The user did in the end assign the Change Request information to all commited files for a View Label. Since user can customize the way Starteam does present its Change Request, you may have to also customize the generated commit to fit your need more closely.

Hope this clarify the effect of using the change-request option.

**Comment by mcoburnwa** [comment]
That clears it up for me, thanks!

Mark Coburn | Senior Software Engineer
global<http://www.globalscape.com/>scape<http://www.globalscape.com/> | NYSE MKT:GSB<http://www.globalscape.com/cgi-bin/links.cgi?page=gsb>
*This communication, including attachments, is for the exclusive use of the addressee and may contain proprietary, confidential or privileged information. If you are not the intended recipient, any use, copying, disclosure, dissemination or distribution is strictly prohibited. If you are not the intended recipient, please notify the sender immediately by return email and delete this communication and destroy all copies.






On Dec 13, 2016, at 5:32 AM, Steve Tousignant <notifications@github.com<mailto:notifications@github.com>> wrote:


To come back on your question. The way CR act on the commit from Starteam is by replacing the message of one or multiple files based on a regular expression. It was design in such a way that one file get the full description of the Change Request in its commit instead of an automated system commit.

The user did in the end assign the Change Request information to all commited files for a View Label. Since user can customize the way Starteam does present its Change Request, you may have to also customize the generated commit to fit your need more closely.

Hope this clarify the effect of using the change-request option.

**Pull request merged**
